server:
  port: 8080
spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://zipkin-server:9411/
    sender:
      type: web
user:
  role: Developer
msg: Hello world - this is from config server Development environment.